name: Night build
on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  push:
    branches:
      - nigth_build
  workflow_dispatch:

jobs:
  run-test:
    uses: ./.github/workflows/pluginTest.yml
    # Если репозитории разные, указывается полный путь: owner/repo/.github/workflows/file.yml@branch

  nightly:
    name: Night build
    needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          ref: nigth_build
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sonar-plugin-jar
          path: build/libs

      - name: Restore file name
        run: echo "PLUGIN_FILE_NAME=${{ needs.run-test.outputs.plugin_file_name }}" >> $GITHUB_ENV

      - name: Save current date
        run: echo "PLUGIN_CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Deploy build
        uses: WebFreak001/deploy-nightly@v3.2.0
        with:
          upload_url: https://uploads.github.com/repos/1c-syntax/sonar-bsl-plugin-community/releases/51033599/assets{?name,label}
          release_id: 51033599
          asset_path: ./build/libs/${{ env.PLUGIN_FILE_NAME }}
          asset_name: sonar-communitybsl-plugin-nightly-${{ env.PLUGIN_CURRENT_DATE }}.jar
          asset_content_type: application/java-archive
          max_releases: 7