name: Plugin Integration Test

on:
  workflow_call: # Позволяет вызывать этот воркфлоу из других файлов
    outputs:
      plugin_file_name:
        description: "The name of the built jar file"
        value: ${{ jobs.integration-test.outputs.plugin_file_name }}
        
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  integration-test:
    runs-on: ubuntu-latest
    outputs:
      plugin_file_name: ${{ steps.set_plugin_info.outputs.plugin_file_name }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Plugin
        run: ./gradlew clean jar

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-plugin-jar
          path: build/libs/*.jar

      - id: set_plugin_info # Добавляем ID, чтобы потом обратиться к outputs этого шага
        name: Start SonarQube server
        run: |
          PLUGIN_JAR=$(find build/libs -name "*.jar" ! -name "*-sources.jar" | head -n 1)
          
          FILE_NAME=$(basename $PLUGIN_JAR)
          echo "plugin_file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          
          docker run -d --name sonarqube -p 9000:9000 \
            -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
            -v "$(pwd)/$PLUGIN_JAR:/opt/sonarqube/extensions/plugins/sonar-communitybsl-plugin.jar" \
            sonarqube:25.4.0.105899-community

      - name: Wait & Setup
        run: |
          until curl -s -f http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do sleep 5; done
          curl -u admin:admin -X POST "http://localhost:9000/api/users/change_password?login=admin&previousPassword=admin&password=Sonar_Password_1"
          RESPONSE=$(curl -u admin:Sonar_Password_1 -s -X POST "http://localhost:9000/api/user_tokens/generate?name=gha-token")
          TOKEN=$(echo $RESPONSE | jq -r '.token')
          echo "SONAR_TOKEN=$TOKEN" >> $GITHUB_ENV
          curl -u admin:Sonar_Password_1 -s -X POST "http://localhost:9000/api/projects/create?name=Test&project=test-project"

      - name: Checkout SSL 3.1
        uses: actions/checkout@v6
        with:
          repository: '1c-syntax/ssl_3_1'
          path: 'target-project'

      - name: Install Sonar scanner
        run: npm install -g sonar-scanner

      - name: SonarQube Scan
        run: |
          sonar-scanner \
              -Dsonar.projectKey=test-project \
              -Dsonar.sources=target-project \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.token=${{ env.SONAR_TOKEN }} \
              -Dsonar.lang.patterns.bsl=**/*.bsl,**/*.os \
              -Dsonar.scm.disabled=true

      - name: Server Logs on Failure
        if: failure()
        run: docker logs sonarqube
